Repository EFUB-LEAD-TOY-2/CLIENT, pull requests merged in 2024-05, with the labels that each got.

#2 # 240512 송지민(songing01) 로그인페이지, 공용푸터 퍼블리싱
  package-lock.json
  package.json
  src/App.js
  src/assets/common/footer/arr.svg
  src/assets/common/footer/footer_escrow.svg
  src/assets/common/footer/location.svg
  src/assets/login/kakao_login.svg
  src/components/common/Footer.jsx
  src/components/common/FooterBtn.jsx
  src/global.css
  src/index.js
  src/pages/LoginPage.jsx
Labels: 📝 documentation, 💄 publishing

#4 #240519 최영서 (YoungseoChoi23) 음반,도서,굿즈 세부페이지, 신촌점 메인페이지 퍼블리싱 완료
  .github/pull_request_template.m
  src/App.js
  src/assets/S_main/arrow_right.svg
  src/assets/S_main/banner.svg
  src/assets/S_main/book1.svg
  src/assets/S_main/book2.svg
  src/assets/S_main/book3.svg
  src/assets/S_main/book4.svg
  src/assets/S_main/close.svg
  src/assets/S_main/cross_section.svg
  src/assets/S_main/goods1.png
  src/assets/S_main/goods2.png
  src/assets/S_main/goods3.png
  src/assets/S_main/goods4.png
  src/assets/S_main/map.svg
  src/assets/S_main/record1.svg
  src/assets/S_main/record2.svg
  src/assets/S_main/record3.svg
  src/assets/S_main/record4.svg
  src/assets/detail/add_photo.svg
  src/assets/detail/cross_section_part.svg
  src/assets/detail/delete.svg
  src/assets/detail/goods_desc.svg
  src/assets/detail/sample_img.svg
  src/assets/detail/small_stars.svg
  src/assets/detail/stars.svg
  src/components/SinchonMain/Category.jsx
  src/components/SinchonMain/GetDirectionModal.jsx
  src/components/SinchonMain/Goods.jsx
  src/components/SinchonMain/GoodsItem.jsx
  src/components/SinchonMain/Record.jsx
  src/components/SinchonMain/SecondHandBook.jsx
  src/components/SinchonMain/SecondHandItem.jsx
  src/components/SinchonMain/SideBar.jsx
  src/components/detail/Detail.jsx
  src/components/detail/DetailTap.jsx
  src/components/detail/DetailTap2.jsx
  src/components/detail/RecordDetailItem.jsx
  src/components/detail/Review.jsx
  src/components/detail/ReviewItem.jsx
  src/pages/SinchonMainPage/SinchonMainPage.jsx
  src/pages/detailPage/BookDetailPage.jsx
  src/pages/detailPage/GoodsDetailPage.jsx
  src/pages/detailPage/RecordDetailPage.jsx
Labels: 💄 publishing

#5 #240521 송지민 (songing01) axios instance 생성, 카카오 로그인 API 연결
  .gitignore
  src/App.js
  src/pages/Login/LoginLoadingPage.jsx
  src/pages/Login/LoginPage.jsx
  src/services/api/client.js
  src/services/api/example.js
Labels: 📝 documentation, ✨ feature

#6 #240523 송지민(songing01) 토큰 저장 오류 해결
  package-lock.json
  package.json
  src/pages/Login/LoginLoadingPage.jsx
  src/services/api/client.js
Labels: 🐛 bugfix

#7 #240531 성혜린(hyerinxx) 공용헤더, 중고매장메인페이지, 도서·음반·상품목록페이지, 장바구니페이지 퍼블리싱
  src/assets/MarketMain/banner-0.png
  src/assets/MarketMain/banner-1.png
  src/assets/MarketMain/banner-2.png
  src/assets/MarketMain/banner-3.png
  src/assets/MarketMain/banner-4.png
  src/assets/MarketMain/banner-5.png
  src/assets/MarketMain/lookup.png
  src/assets/MarketMain/main-banner-btn-left.svg
  src/assets/MarketMain/main-banner-btn-right.svg
  src/assets/MarketMain/plus-circle.svg
  src/assets/MarketMain/sub-banner-01.png
  src/assets/MarketMain/sub-banner-02.png
  src/assets/MarketMain/sub-banner-03.png
  src/assets/common/header/market_logo.png
  src/components/CartPage/Item.jsx
  src/components/CartPage/dummy.jsx
  src/components/ListPage/Category.jsx
  src/components/ListPage/Item.jsx
  src/components/ListPage/List.jsx
  src/components/ListPage/ListStyle.jsx
  src/components/ListPage/Pagination.jsx
  src/components/ListPage/Sidebar.jsx
  src/components/ListPage/Sort.jsx
  src/components/ListPage/dummy.jsx
  src/components/MarketMain/Banner.jsx
  src/components/MarketMain/Info.jsx
  src/components/MarketMain/List.jsx
  src/components/MarketMain/Lookup.jsx
  src/components/MarketMain/Qna.jsx
  src/components/MarketMain/SalesUpdate.jsx
  src/components/MarketMain/StoreNavigation.jsx
  src/components/common/ButtonBlue.jsx
  src/components/common/Header.jsx
  src/pages/BookListPage.jsx
  src/pages/CartPage.jsx
  src/pages/GoodsListPage.jsx
  src/pages/Login/LoginPage.jsx
  src/pages/MarketMainPage.jsx
  src/pages/MusicListPage.jsx
  src/reset.css
Labels: 💄 publishing

#8 #240531 성혜린(hyerinxx) 라우팅, 폴더 정리, 소소한 오류 해결
  src/App.js
  src/components/ListPage/Category.jsx
  src/components/ListPage/List.jsx
  src/components/ListPage/Pagination.jsx
  src/components/ListPage/Sidebar.jsx
  src/components/ListPage/Sort.jsx
  src/components/MarketMain/Info.jsx
  src/components/MarketMain/List.jsx
  src/components/MarketMain/Lookup.jsx
  src/components/MarketMain/Qna.jsx
  src/components/MarketMain/SalesUpdate.jsx
  src/components/MarketMain/StoreNavigation.jsx
  src/pages/CartPage/CartPage.jsx
  src/pages/MarketMainPage/MarketMainPage.jsx
  src/pages/listPage/BookListPage.jsx
  src/pages/listPage/GoodsListPage.jsx
  src/pages/listPage/MusicListPage.jsx
Labels: 🐛 bugfix, 📝 documentation, ✨ feature

#9 240531 송지민(songing01) 상품 리스트, 장바구니 관련 페이지 API 연결, 페이지연결 및 ui 수정
  src/App.js
  src/components/CartPage/Item.jsx
  src/components/ListPage/Item.jsx
  src/components/ListPage/List.jsx
  src/components/ListPage/Sort.jsx
  src/components/SinchonMain/Category.jsx
  src/components/SinchonMain/GoodsItem.jsx
  src/components/SinchonMain/SecondHandItem.jsx
  src/components/common/ButtonBlue.jsx
  src/components/common/Header.jsx
  src/components/detail/Detail.jsx
  src/components/detail/DetailTap.jsx
  src/components/detail/RecordDetailItem.jsx
  src/pages/CartPage/CartPage.jsx
  src/pages/SinchonMainPage/SinchonMainPage.jsx
  src/pages/detailPage/BookDetailPage.jsx
  src/pages/detailPage/GoodsDetailPage.jsx
  src/pages/detailPage/RecordDetailPage.jsx
  src/pages/listPage/BookListPage.jsx
  src/pages/listPage/GoodsListPage.jsx
  src/pages/listPage/MusicListPage.jsx
  src/services/api/carts.js
  src/services/api/list.js
Labels: 🐛 bugfix, ✨ feature, 💄 publishing

#10 240531 송지민 (songing01) 검색 API 연결
  src/App.js
  src/components/CartPage/Item.jsx
  src/components/ListPage/SearchedItem.jsx
  src/components/common/Header.jsx
  src/pages/Login/LoginPage.jsx
  src/pages/SinchonMainPage/SinchonMainPage.jsx
  src/pages/detailPage/BookDetailPage.jsx
  src/pages/detailPage/GoodsDetailPage.jsx
  src/pages/detailPage/RecordDetailPage.jsx
  src/pages/listPage/SearchedPage.jsx
  src/services/api/search.js
Labels: 🐛 bugfix, ✨ feature, 💄 publishing
